# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do

    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "40"

  end

  desc "Test"
  lane :tests do
    run_tests(
      scheme: "TestCI",
      code_coverage: false,
      output_directory: 'output',
      device: "iPhone 12",
      deployment_target_version: "15.2",
      result_bundle: true,
      skip_detect_devices: true
      )
  end
end
